### ISSUE TITLE
微博接口 2/statuses/share 调用失败

### ISSUE THREAD

**Issue by zzy131250** [michaelliao/sinaweibopy#58]
最近微博更新了接口，使用 2/statuses/share 发送微博，导致上传一张照片并发送微博的功能无法使用，错误如下：
```Python
Traceback (most recent call last):
  File "./send_message.py", line 110, in <module>
    send_msg_with_pic(client, 'table.png', get_city_data(city))
  File "./send_message.py", line 64, in send_msg_with_pic
    client.statuses.share.post(status=message, pic=f)
  File "/home/zhouzy/.pyenv/versions/2.7.13/lib/python2.7/site-packages/weibo.py", line 310, in __call__
    return _http_call('%s%s.json' % (self._client.api_url, self._path), method, self._client.access_token, **kw)
  File "/home/zhouzy/.pyenv/versions/2.7.13/lib/python2.7/site-packages/weibo.py", line 172, in _http_call
    raise APIError(r.error_code, r.get('error', ''), r.get('request', ''))
weibo.APIError: APIError: 10017: appkey not bind domain!, request: /2/statuses/share.json
```
提示的是appkey没有绑定域名，但是已经绑定了域名，且域名写在微博文本中。
另外，仅发送文本，不发送图片是可以成功发送的。
希望能够解决，谢谢！

**Comment by zharuosi** [comment]
我也遇到这个问题，请问解决了吗？

**Comment by zzy131250** [comment]
@zharuosi 你好，已经解决了，可以参考下[这个api](https://github.com/lxyu/weibo/blob/master/weibo.py)，自己写个函数就好啦

**Comment by zharuosi** [comment]
谢谢！
